const APP_CONFIG = {
  BASE_YEAR_CARBON: process.env.REACT_APP_BASE_YEAR_CARBON || '2016',
  BASE_YEAR_WATER: process.env.REACT_APP_BASE_YEAR_WATER || '2016',
  BASE_YEAR_ELECTRICITY: process.env.REACT_APP_BASE_YEAR_ELECTRICITY || '2020',
  BASE_YEAR_UNIT_ELECTRICITY: process.env.REACT_APP_BASE_YEAR_UNIT_ELECTRICITY || '2020',
  BASE_YEAR_WASTE: process.env.REACT_APP_BASE_YEAR_WASTE || '2018',
};

export default APP_CONFIG;
